{
 "title": "Kafka Metrics",
 "description": "Dashboard for jmx_exporter",
 "tags": [ "kafka" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": "label_values(kafka_controller_KafkaController_Value, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_controller_KafkaController_Value{job=\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_server_BrokerTopicMetrics_Count{job=\"$job\"}, topic)"
   },
   {
    "name": "online_broker",
    "query": "query_result(count(up{job=~\"$job\"}))"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers Online",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(kafka_server_KafkaServer_Value{job=~\"$job\",name=\"BrokerState\"})"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"$job\",name=\"GlobalTopicCount\"})"
    }
   ]
  },
  {
   "title": "Total of Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=\"$job\",name=\"GlobalPartitionCount\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_controller_KafkaController_Value{job=~\"$job\",name=\"ActiveControllerCount\"})"
    }
   ]
  },
  {
   "title": "Under Min Isr Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=~\"$job\",name=\"UnderMinIsrPartitionCount\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_ReplicaManager_Value{job=~\"$job\",name=\"UnderReplicatedPartitions\",instance=~\"$instance\"}) "
    }
   ]
  },
  {
   "title": "Messages/sec",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum by(topic)(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",topic=~\"$topic\",name=\"MessagesInPerSec\",partition!~\".+\"}))",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "BytesIn/sec",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",topic!=\"\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesInPerSec\",partition!~\".+\"})by(instance))/1024/1024",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "BytesOut/sec",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(sum(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",topic!=\"\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesOutPerSec\",partition!~\".+\"})by(instance))/1024/1024",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "Producer Total Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"Produce\",job=\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "FetchConsumer Total Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"FetchConsumer\",job=\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Total Time"
    }
   ]
  },
  {
   "title": "FetchFollower Total Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"FetchFollower\",job=\"$job\",instance=~\"$instance\"})",
     "legendFormat": "Total Time"
    }
   ]
  },
  { "title": "Broker Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",topic=~\"$topic\",name=\"MessagesInPerSec\",partition!~\".+\"})",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",topic!=\"\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesInPerSec\",partition!~\".+\"})by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesOutPerSec\",partition!~\".+\"})by(topic)",
     "legendFormat": "Topic: {{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Message/s" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",topic=~\"$topic\",name=\"MessagesInPerSec\",partition!~\".+\"})",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",topic!=\"\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesInPerSec\",partition!~\".+\"})by(instance)",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Instance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum (kafka_server_BrokerTopicMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",topic=~\"$topic\",name=\"BytesOutPerSec\",partition!~\".+\"})by(instance)",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Produce Request rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(kafka_network_RequestMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",name=\"RequestsPerSec\",request=\"Produce\"})",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Request rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(kafka_network_RequestMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",name=\"RequestsPerSec\",request=\"Fetch\"})",
     "legendFormat": "Instance: {{ instance }}"
    }
   ]
  },
  {
   "title": "FetchFollower Request rate ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(kafka_network_RequestMetrics_OneMinuteRate{job=\"$job\",instance=~\"$instance\",name=\"RequestsPerSec\",request=\"FetchFollower\"})",
     "legendFormat": "Instance: {{ instance }}"
    }
   ]
  },
  {
   "title": "Leader Count Per Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$job\",instance=~\"$instance\",name=\"LeaderCount\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Partition Count Per Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{job=\"$job\",instance=~\"$instance\",name=\"PartitionCount\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Isr Shrinks Per Sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_OneMinuteRate{job=\"$job\",instance=~\"$instance\",name=\"IsrShrinksPerSec\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Request Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_RequestChannel_Value{job=\"$job\",instance=~\"$instance\",name=\"RequestQueueSize\",processor!~\".+\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Response Queue Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_RequestChannel_Value{job=\"$job\",instance=~\"$instance\",name=\"ResponseQueueSize\",processor!~\".+\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Request Handler Avg Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_KafkaRequestHandlerPool_OneMinuteRate{job=\"$job\",instance=~\"$instance\",name=\"RequestHandlerAvgIdlePercent\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "java_lang_Threading_ThreadCount{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used{job=\"$job\",instance=~\"$instance\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Network Processor Avg Idle",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_SocketServer_Value{job=\"$job\",instance=~\"$instance\",name=\"NetworkProcessorAvgIdlePercent\"}",
     "legendFormat": "Instance: {{instance}}"
    }
   ]
  },
  {
   "title": "Producer Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Produce RequestQueueTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"RequestQueueTimeMs\",request=\"Produce\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Produce LocalTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"LocalTimeMs\",request=\"Produce\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Produce RemoteTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"RemoteTimeMs\",request=\"Produce\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Produce ResponseQueueTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"ResponseQueueTimeMs\",request=\"Produce\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "Produce ResponseSendTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"ResponseSendTimeMs\",request=\"Produce\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FetchConsumer Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "collapsed": true,
   "panels": [
    {
     "title": "FetchConsumer RequestQueueTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"RequestQueueTimeMs\",request=\"FetchConsumer\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer LocalTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"LocalTimeMs\",request=\"FetchConsumer\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer RemoteTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"RemoteTimeMs\",request=\"FetchConsumer\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer ResponseQueueTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"ResponseQueueTimeMs\",request=\"FetchConsumer\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer ResponseSendTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"ResponseSendTimeMs\",request=\"FetchConsumer\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "FetchFollower Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "collapsed": true,
   "panels": [
    {
     "title": "FetchFollower RequestQueueTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"RequestQueueTimeMs\",request=\"FetchFollower\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower LocalTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"LocalTimeMs\",request=\"FetchFollower\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower RemoteTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"RemoteTimeMs\",request=\"FetchFollower\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower ResponseQueueTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"ResponseQueueTimeMs\",request=\"FetchFollower\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollower ResponseSendTimeMs",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_95thPercentile{job=\"$job\",instance=~\"$instance\",name=\"ResponseSendTimeMs\",request=\"FetchFollower\"}",
       "legendFormat": "Instance: {{instance}}"
      }
     ]
    }
   ]
  }
 ]
}